### ISSUE TITLE
arraySumAdjacentDifference

### ISSUE THREAD

**Issue by setco-website** [setco-website/Java-Hacktoberfest#5]
Given array of integers, find the sum of absolute differences of consecutive numbers.

Example

For `inputArray = [4, 7, 1, 2]`, the output should be
`arraySumAdjacentDifference(inputArray) = 10`.

* `|4 - 7| = 3`;
* `|7 - 1| = 6`;
* `|1 - 2| = 1`

So, the answer is `3 + 6 + 1 = 10`.

Input/Output

* **[execution time limit] 3 seconds (java)**

* **[input] array.integer inputArray**

  *Guaranteed constraints:*
  `3 ≤ inputArray.length ≤ 10`,
  `1 ≤ inputArray[i] ≤ 15`.

* **[output] integer**

  * Sum of absolute differences of consecutive numbers from `inputArray`.

**[Java] Syntax Tips**

```java
// Prints help message to the console
// Returns a string
// 
// Globals declared here will cause a compilation error,
// declare variables inside the function instead!
String helloWorld(String name) {
    System.out.println("This prints to the console when you Run Tests");
    return "Hello, " + name;
}
```

**Comment by PrathibhaS** [comment]
#7
